### ISSUE TITLE
Add redirection from http:// to https:// on arguman.org

### ISSUE THREAD

**Issue by KrzysztofMadejski** [arguman/arguman.org#336] opened 2017-07-17 11:31 UTC
Now creating a https certificate is super-easy and free with https://certbot.eff.org/.

Let me know if you need help with setting that up. PS. Multiple domain are not supported so for each language a separate certificate is needed.

`./certbot-auto --cert-name arguman -d arguman.org -d en.arguman.org -d fr.arguman.org -d tr.arguman.org -d ch.arguman.org -d pl.arguman.org` should get it going

**Comment by fatiherikli** [comment] 2017-08-09 12:50
Actually we have a certificate thanks to cloudflare, all we need to to is adding a redirection middleware on django. 

This should work for instance: https://en.arguman.org

**Comment by KrzysztofMadejski** [comment] 2017-08-09 13:15
Cool! I've changed the title.

I'm doing it most often on the webserver configuration.
```
RewriteCond %{HTTPS} off 
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
```
Should work if you have access to Apache.

**Comment by fatiherikli** [comment] 2017-08-09 14:20
Make sense, you're right. Django middleware is not necessary in that case. We use Nginx instead of Apache but the configuration is not much different.

**Comment by iangilman** [comment] 2017-12-28 06:13
I came here to report this (since my browser warned me that your registration form was insecure, and I knew to try HTTPS, but your average user may not), but since it's already reported,  I'm just bumping the thread. :-)

**Comment by iangilman** [comment] 2018-12-02 01:04
Is this fixed now? It doesn't seem to be, but maybe the fix hasn't been deployed yet?

**Comment by fatiherikli** [comment] 2018-12-02 16:56
Hey @iangilman 

Can you send me a reproduction url? I need to check what is wrong. It's configuration my CloudFlare. I don't do anything on server side except signing the certificates.

**Comment by iangilman** [comment] 2019-01-07 04:12
Apologies for the delayed response! Anyway, if I go here:

http://en.arguman.org/login/

It doesn't automatically forward me to the HTTPS version of that page, which it should. Tested just now on Mac Firefox.

**Comment by fatiherikli** [comment] 2019-01-09 01:44
Got it, thanks! I'll fix that soon, mate :)

**Comment by iangilman** [comment] 2019-01-09 02:12
Awesome. I love the site! :-)

**Comment by fatiherikli** [comment] 2019-01-17 19:51
This is done!

**Comment by fatiherikli** [comment] 2019-01-17 19:51
Try: http://en.arguman.org

**Closed by fatiherikli** 2019-01-17 19:51 UTC

**Comment by iangilman** [comment] 2019-02-16 23:40
Beautiful, looks good! Thank you :-)
